GET http://localhost:5000/echo

### users
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "11223344",
    "role": "user",
    "dateOfBirth": "1990-01-01",
    "profileImage": "https://www.google.com"
}



### roles
POST http://localhost:5000/api/roles
Content-Type: application/json

{
    "name": "user"
}

###
GET http://localhost:5000/api/roles
